# Welcome to numpy tutorial

In [2]:
import numpy as np

In [8]:
myarr = np.array([[3,6,32,7]], np.int8)

In [9]:
myarr

array([[ 3,  6, 32,  7]], dtype=int8)

In [11]:
myarr[0,1]

6

In [12]:
myarr.shape

(1, 4)

In [13]:
myarr.dtype

dtype('int8')

In [14]:
myarr[0,1] = 45

In [15]:
myarr

array([[ 3, 45, 32,  7]], dtype=int8)

# Conversion from other python structure

In [3]:
listarray = np.array([[1,2,3], [5,8,5], [0,3,1]])

In [4]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [5]:
listarray.dtype

dtype('int32')

In [6]:
listarray.shape

(3, 3)

In [7]:
listarray.size

9

# Intrinsic numpy array creation objects

In [8]:
zeros = np.zeros((2,5))

In [10]:
zeros.dtype

dtype('float64')

In [11]:
zeros.shape

(2, 5)

In [12]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
rng = np.arange(15)

In [15]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
lspace = np.linspace(1,4,5)

In [24]:
lspace

array([1.  , 1.75, 2.5 , 3.25, 4.  ])

In [25]:
emp = np.empty((4,6))

In [26]:
emp

array([[5.06027069e-290, 4.67296746e-307, 1.69121096e-306,
        7.56605918e-307, 1.95819673e-306, 7.56569929e-307],
       [1.89146896e-307, 7.56571288e-307, 4.00544531e-307,
        1.11261095e-306, 3.56043054e-307, 1.37961641e-306],
       [2.22518251e-306, 1.33511969e-306, 1.69118108e-306,
        8.06632139e-308, 1.20160711e-306, 1.69119330e-306],
       [1.24611674e-306, 1.29060871e-306, 6.89805151e-307,
        1.78020169e-306, 1.42410974e-306, 2.56761491e-312]])

In [27]:
emp_like = np.empty_like(lspace)

In [28]:
emp_like

array([1.  , 1.75, 2.5 , 3.25, 4.  ])

In [29]:
ide = np.identity(45)

In [30]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [31]:
ide.shape

(45, 45)

In [32]:
arr = np.arange(99)

In [33]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [36]:
arr = arr.reshape(3, 33)

In [37]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [40]:
arr = arr.ravel()

In [41]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [42]:
arr.shape

(99,)